version: '3.8'

services:
  database:
    image: 'mysql:8.0.31'
    container_name: 'database'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=portal
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    ports:
      - 3306:3306
    #volumes: db:
     #- './volumes/database/data:/var/lib/mysql'

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$YOUR_DB_NAME
      - SPRING_DATASOURCE_USERNAME=$YOUR_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$YOUR_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "$LOCAL_PORT:$DOCKER_PORT"
