version: '3.8'

services:
  database:
    image: 'mysql:8.0.31'
    container_name: 'documents_db'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=portal
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes: 
      - './volumes/database/data:/var/lib/mysql'
      - './volumes/database/dump/users.sql:/docker-entrypoint-initdb.d/datadump.sql'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    container_name: 'documents_app'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://documents_db:3306/portal
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
